//AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_FINISH = 'AUTH_FINISH';
export const AUTH_FAIL = 'AUTH_FAIL'; 
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//USER
export const USER_START = 'USER_START';
export const USER_FINISH = 'USER_FINISH';
export const USER_FAIL = 'USER_FAIL'; 
export const USER_SUCCESS= 'USER_SUCCESS';

//BOOKMARK
export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const FETCH_BOOKMARK = 'FETCH_BOOKMARK';

//GOOGLE
export const FETCH_GOOGLE_SUGGESTIONS = 'FETCH_GOOGLE_SUGGESTIONS';
export const FETCH_GOOGLE_RESULTS = 'FETCH_GOOGLE_RESULTS';

//GIFT
export const NEW_GIFT = 'NEW_GIFT';
export const FETCH_GIFTS = 'FETCH_GIFTS';
export const GIFT_START = 'GIFT_START';
export const GIFT_FINISH = 'GIFT_FINISH';
export const GIFT_FAIL = 'GIFT_FAIL'; 
export const GIFT_SUCCESS= 'GIFT_SUCCESS';

//WIDGETS SETTING
export const UPDATE_WIDGETS = 'UPDATE_WIDGETS';
export const FETCH_WIDGETS = 'FETCH_WIDGETS';

//ADS
export const CHECK_AD_BLOCKS = 'CHECK_AD_BLOCKS';
export const ADS_FAIL = 'ADS_FAIL';